config/routes.rb
# frozen_string_literal: true
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  root 'questions#index'

  resources :attachments, only: %i[destroy]
  resources :links, only: %i[destroy]
  resources :earned_rewards, only: %i[index]

  resources :questions do
    resources :answers, shallow: true, only: %i[create destroy update edit new] do
      get 'set_best', on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [] do
        get :me, on: :collection
      end
      resources :questions, only: %i[create update destroy index show] do
        resources :answers, shallow: true, only: %i[create update destroy show]
      end
    end
  end

  mount ActionCable.server => '/cable'
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
  belongs_to :author, class_name: 'User'
  has_many_attached :files
  has_many :links, dependent: :destroy, as: :linkable
  has_one :reward, dependent: :destroy
  belongs_to :best_answer, class_name: 'Answer', optional: true

  accepts_nested_attributes_for :links, reject_if: :all_blank
  accepts_nested_attributes_for :reward, reject_if: :all_blank

  validates :title, :body, presence: true
  validates :title, uniqueness: true

  def author?(user)
    author == user
  end

  def set_best_answer(answer)
    return nil unless related?(answer)

    previous_answer = best_answer
    self.best_answer = answer
    answer.author.rewards.push(reward) if reward && !answer.author.has_reward?(reward)
    save!

    previous_answer
  end

  private

  def related?(obj)
    self == obj.question
  end
end

app/controllers/api/v1/questions_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class QuestionsController < Api::V1::BaseController
      # after_action :publish_question, only: :create

      def index
        @questions = Question.all
        render json: @questions, each_serializer: QuestionsSerializer
      end

      def create
        @question = Question.create(question_params)
        if @question.persisted?
          head :created
        else
          head :unprocessable_entity
        end
      end

      def update
        if question.update(question_params)
          head :ok
        else
          head :unprocessable_entity
        end
      end

      def show
        render json: question
      end

      def destroy
        question.destroy
        head :ok
      end

      private

      def question
        @question = Question.find(params[:id])
      end

      def question_params
        params.require(:question).permit(:title, :body, :author_id)
      end

      # def publish_question
      #   return if @question.persisted?
      #
      #   ActionCable.server.broadcast(
      #     'questions',
      #     ApplicationController.render(partial: 'questions/question_light', locals: { question: @question })
      #   )
      # end
    end
  end
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  after_action :publish_question, only: %i[create]

  expose :questions, -> { Question.with_attached_files.all }
  expose :question, find: ->(id, scope) { scope.with_attached_files.find(id) }
  expose :answers, -> { question.answers.all }

  authorize_resource
  # load_and_authorize_resource

  def new
    question.links.new
    question.build_reward
  end

  def show
    @answer = Answer.new
  end

  def index; end

  def create
    respond_to do |format|
      if question.save
        flash.now[:success] = 'Your question successfully created'
        format.turbo_stream
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if question.update(question_params)
        flash.now[:success] = 'Your question successfully updated'
        format.turbo_stream
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      question.destroy
      flash.now[:success] = 'Your question successfully deleted'
      format.turbo_stream
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :body, :author_id, files: [], links_attributes: %i[name url],
                                                                reward_attributes: %i[title image])
  end

  def publish_question
    return if question.errors.any?

    ActionCable.server.broadcast(
      'questions',
      ApplicationController.render(partial: 'questions/question_light', locals: { question: question })
    )
  end
end

app/helpers/questions_helper.rb
# frozen_string_literal: true

module QuestionsHelper
end

app/views/questions/_form.html.slim
= turbo_frame_tag question do
  = form_with model: question do |form|
    = render 'shared/errors', resource: question
    p
      = form.label :title
      = form.text_field :title
    p
      = form.label :body
      = form.text_area :body, id: :question_body, rows: 7, cols: 60

    p = form.hidden_field :author_id, value: current_user&.id

    p
      = form.label :files
      = form.file_field :files, multiple: true, direct_upload: true

    p Links
    p = form.simple_fields_for :links do |links_form|
      = links_form.input :name, multiple: true
      = links_form.input :url

    p Reward
    p = form.simple_fields_for :reward do |reward_form|
      = reward_form.input :title
      = reward_form.label :image
      = reward_form.file_field :image

    p = form.submit 'Ask'

app/views/questions/_question.html.slim
= turbo_frame_tag question do
  div
    p = link_to question.title, question_path(question), data: { turbo_frame: '_top'}
    p = question.body
    p = question.answers.size
    .files
      - if question.files.attached?
        - question.files.each do |file|
          = link_to file.filename.to_s, url_for(file)
          = ' - '
          = link_to 'Delete file', attachment_path(file), data: {turbo_method: :delete, turbo_confirm: t('confirm.delete.file')}
          = '     '
    .links
      p
        - if question.links.present?
          - question.links.each do |link|
            = link_to link.name, link.url
            - if question.author?(current_user)
              | (
              = link_to 'Delete link', link, data: { turbo_method: :delete, turbo_confirm: t('confirm.delete.link') }
              | )
            =  ' '
    - if question.author?(current_user)
      p = link_to 'Edit', edit_question_path(question)
      p = link_to 'Delete question', question, data: {turbo_method: :delete, turbo_confirm: t('confirm.delete.question')}

app/views/questions/_question_light.html.slim
= turbo_frame_tag question do
  div
    p = link_to question.title, question_path(question), data: { turbo_frame: '_top'}
    p = question.body
    p = question.answers.size
    .files
      - if question.files.attached?
        - question.files.each do |file|
          = link_to file.filename.to_s, url_for(file)
          = ' - '
          = link_to 'Delete file', attachment_path(file), data: {turbo_method: :delete, turbo_confirm: t('confirm.delete.file')}
          = '     '
    .links
      p
        - if question.links.present?
          - question.links.each do |link|
            = link_to link.name, link.url
            - if question.author?(current_user)
              | (
              = link_to 'Delete link', link, data: { turbo_method: :delete, turbo_confirm: t('confirm.delete.link') }
              | )
            =  ' '

app/views/questions/create.turbo_stream.slim
= turbo_stream.prepend 'questions', render(question)
= turbo_stream.prepend('flash', partial: 'shared/flash')

app/views/questions/destroy.turbo_stream.slim
= turbo_stream.remove question
= turbo_stream.prepend('flash', partial: 'shared/flash')

app/views/questions/edit.html.slim
= render 'form'

app/views/questions/index.html.slim
= turbo_frame_tag Question.new
 div = link_to 'Ask question', new_question_path, data: { turbo_frame: dom_id(Question.new) }

= turbo_frame_tag 'questions'
  = render questions

app/views/questions/new.html.slim
= render 'form'

app/views/questions/show.html.slim
= content_tag :div, id: "question-#{question.id}"
  h1 = question.title
  p = question.body

  .reward
    - if question.reward.present?
      h2 Reward
      p = question.reward.title
      - if question.reward.image.present?
        img src="#{url_for(question.reward.image)}" width=200 height=200
  .links
    - if question.links.present?
      h2 Links
      ul
        - question.links.each do |link|
          li
            = link_to link.name, link.url

  .files
    - if question.files.attached?
      - question.files.each do |file|
        p = link_to file.filename.to_s, url_for(file)

  - if question.author?(current_user)
    p = link_to 'Delete question', question, method: :delete

  h2 Reply your answer

  - if user_signed_in?
    = turbo_frame_tag Answer.new do
      div = link_to 'Reply answer', new_question_answer_path(question), data: { turbo_frame: dom_id(Answer.new) }

  - else
    p
      | You need to
      = ' '
      = link_to 'log in', new_user_session_path

  .answers
    h2 Answers
    = turbo_frame_tag 'answers' do
      = render question.answers

app/views/questions/update.turbo_stream.slim
= turbo_stream.replace question, render(question)
= turbo_stream.prepend('flash', partial: 'shared/flash')