config/routes.rb
# frozen_string_literal: true
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  root 'questions#index'

  resources :attachments, only: %i[destroy]
  resources :links, only: %i[destroy]
  resources :earned_rewards, only: %i[index]

  resources :questions do
    resources :answers, shallow: true, only: %i[create destroy update edit new] do
      get 'set_best', on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [] do
        get :me, on: :collection
      end
      resources :questions, only: %i[create update destroy index show] do
        resources :answers, shallow: true, only: %i[create update destroy show]
      end
    end
  end

  mount ActionCable.server => '/cable'
end

app/views/shared/_errors.html.slim
- if resource&.errors.present?
  b= "#{resource.errors.count} errors detected: "
  ul
    - resource.errors.full_messages.each do |message|
      li= message

app/views/shared/_flash.html.slim
- if flash.present?
  - flash.each do |key, message|
    = content_tag :p, message.html_safe, class: "alert alert-primary d-flex align-items-center", role: key

app/views/shared/_header.html.slim
- if user_signed_in?
  p
    = "Hi, #{current_user.name}! #{current_user.email} "
    img src="#{current_user.image_url}" width=50 height=50
    = ' '
    = link_to('Logout', destroy_user_session_path, method: :delete)
    = ' | '
    = link_to('Rewards', earned_rewards_path)



- else
  p
    = link_to('Log in', new_user_session_path)

app/views/shared/answer_update.turbo_stream.slim
- answer = @record
= turbo_stream.replace answer, render(answer, question: answer.question)
= turbo_stream.prepend('flash', partial: 'shared/flash')

app/views/shared/need_login.turbo_stream.slim
= turbo_stream.prepend('flash', partial: 'shared/flash')

app/views/shared/question_update.turbo_stream.slim
- question = @record
= turbo_stream.replace question, render(question)
= turbo_stream.prepend('flash', partial: 'shared/flash')