config/routes.rb
# frozen_string_literal: true
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  root 'questions#index'

  resources :attachments, only: %i[destroy]
  resources :links, only: %i[destroy]
  resources :earned_rewards, only: %i[index]

  resources :questions do
    resources :answers, shallow: true, only: %i[create destroy update edit new] do
      get 'set_best', on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [] do
        get :me, on: :collection
      end
      resources :questions, only: %i[create update destroy index show] do
        resources :answers, shallow: true, only: %i[create update destroy show]
      end
    end
  end

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :author, class_name: 'User'
  has_many_attached :files
  has_many :links, dependent: :destroy, as: :linkable

  accepts_nested_attributes_for :links, reject_if: :all_blank

  validates :body, presence: true

  def author?(user)
    author == user
  end

  def best?
    self == question.best_answer
  end
end

app/controllers/answers_controller.rb
# frozen_string_literal: true

class AnswersController < ApplicationController
  before_action :authenticate_user!

  before_action :question, only: %i[create new]
  before_action :set_new_links, only: %i[new edit]
  after_action :publish_answers, only: %i[create]

  expose :answers, -> { question.answers }
  expose :answer

  authorize_resource

  def create
    @answer = answers.new(answer_params)
    respond_to do |format|
      if @answer.save
        flash.now[:success] = 'Your answer successfully created'
        format.turbo_stream
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if answer.update(answer_params)
        flash.now[:success] = 'Your answer successfully updated'
        format.turbo_stream
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      answer.destroy
      flash.now[:success] = 'Your answer successfully deleted'
      format.turbo_stream
    end
  end

  def set_best
    authorize! :set_best, answer
    @previous_answer = answer.question.set_best_answer(answer)
    redirect_to answer.question
    # respond_to do |format|
    #   flash.now[:success] = 'Your link successfully deleted'
    #   format.turbo_stream
    # end
  end

  private

  def question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body, :question_id, :author_id, files: [], links_attributes: %i[name url])
  end

  def set_new_links
    answer.links.new
  end

  def publish_answers
    return if answer.errors.any?

    ActionCable.server.broadcast(
      'answers',
      { body: ApplicationController.render(partial: 'answers/answer_light', locals: { answer: @answer }),
        question: question.id }
    )
  end
end

app/controllers/api/v1/answers_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class AnswersController < Api::V1::BaseController
      # after_action :publish_answer, only: :create

      def create
        @answer = question.answers.new(answer_params)
        if @answer.save
          head :created
        else
          head :unprocessable_entity
        end
      end

      def update
        if answer.update(answer_params)
          head :ok
        else
          head :unprocessable_entity
        end
      end

      def show
        render json: answer
      end

      def destroy
        answer.destroy
        head :ok
      end

      private

      def answer
        @answer = Answer.find(params[:id])
      end

      def answer_params
        params.require(:answer).permit(:title, :body, :author_id)
      end

      def question
        @question = Question.find(params[:question_id])
      end

      # def publish_answer
      #   return if @answer.persisted?
      #
      #   ActionCable.server.broadcast(
      #     'answers',
      #     ApplicationController.render(partial: 'answers/answer_light', locals: { answer: @answer })
      #   )
      # end
    end
  end
end

app/helpers/answers_helper.rb
# frozen_string_literal: true

module AnswersHelper
end

app/views/answers/_answer.html.slim
= turbo_frame_tag answer do
  div
    p
      - if answer.best?
        = 'BEST --> '
      = answer.body
      = ' '
      = link_to 'Best', set_best_answer_path(answer) if can? :set_best, answer
    .files
      - if answer.files.attached?
        p
          - answer.files.each do |file|
            = link_to file.filename.to_s, url_for(file)
            = ' - '
            = link_to 'Delete file', attachment_path(file), data: { turbo_method: :delete, turbo_confirm: t('confirm.delete.file') }
            = '     '
    .links
      p
        - if answer.links.present?
          | Links-->
          - answer.links.each do |link|
            = link_to link.name, link.url
            - if answer.author?(current_user)
              | (
              = link_to 'Delete link', link, data: { turbo_method: :delete, turbo_confirm: t('confirm.delete.link') }
              | )
            = ' '
    .actions
      p
        - if answer.author?(current_user)
          = link_to 'Delete answer', answer, data: { turbo_method: :delete,  turbo_confirm: t('confirm.delete.answer') }
          = ' '
          = link_to 'Edit', edit_answer_path(answer)

app/views/answers/_answer_light.html.slim
= turbo_frame_tag answer do
  div
    p
      - if answer.best?
        = 'BEST --> '
      = answer.body
    .files
      - if answer.files.attached?
        p
          - answer.files.each do |file|
            = link_to file.filename.to_s, url_for(file)
            = ' - '
            = link_to 'Delete file', attachment_path(file), data: { turbo_method: :delete, turbo_confirm: t('confirm.delete.file') }
            = '     '
    .links
      p
        - if answer.links.present?
          | Links-->
          - answer.links.each do |link|
            = link_to link.name, link.url
            - if answer.author?(current_user)
              | (
              = link_to 'Delete link', link, data: { turbo_method: :delete, turbo_confirm: t('confirm.delete.link') }
              | )
            = ' '

app/views/answers/_form.html.slim
= turbo_frame_tag answer do
  = form_with model: [@question, answer] do |form|
    = render 'shared/errors', resource: @answer

    p
      = form.label :body
      br = form.text_area :body, id: :answer_body, rows: 3, cols: 60

    p = form.hidden_field :question_id

    p = form.hidden_field :author_id, value: current_user&.id

    p
      = form.label :files
      = form.file_field :files, multiple: true, direct_upload: true

    p Links
    p = form.fields_for :links do |l|
      p
        = l.label :name, "Link name"
        = l.text_field :name
      p
        = l.label :url
        = l.text_field :url

    p = form.submit 'Reply'

app/views/answers/create.turbo_stream.slim
= turbo_stream.prepend 'answers', render(@answer, question: @answer.question)
= turbo_stream.prepend('flash', partial: 'shared/flash')

app/views/answers/destroy.turbo_stream.slim
= turbo_stream.remove answer
= turbo_stream.prepend('flash', partial: 'shared/flash')

app/views/answers/edit.html.slim
= render 'form'

app/views/answers/set_best.turbo_stream.slim
= turbo_stream.replace answer, render(answer, question: answer.question)
= turbo_stream.replace answer, render(@previous_answer, question: @previous_answer.question) if @previous_answer
= turbo_stream.prepend('flash', partial: 'shared/flash')

app/views/answers/update.turbo_stream.slim
= turbo_stream.replace answer, render(answer, question: answer.question)
= turbo_stream.prepend('flash', partial: 'shared/flash')